king:
	pytest -v -s --durations=0 test_simple.py::test_king_mask


testpower:
	pytest -v -s --durations=0 test_power.py

testfibo:
	pytest -v -s --durations=0 test_fibo.py

testprime:
	pytest -v -s --durations=0 test_simple.py
