king:
	pytest -v -s --durations=0 test_simple.py::test_king_mask
horse:
	pytest -v -s --durations=0 test_simple.py::test_horse_mask
rook:
	pytest -v -s --durations=0 test_simple.py::test_rook_mask
bishop:
	pytest -v -s --durations=0 test_simple.py::test_bishop_mask