bubble:
	pytest -v -s --durations=0 test_sorts.py::test_bubble_sort
bubble_exchange:
	pytest -v -s --durations=0 test_sorts.py::test_bubble_with_count_exchange
insertion:
	pytest -v -s --durations=0 test_sorts.py::test_insertion_sort
insertion_shift:
	pytest -v -s --durations=0 test_sorts.py::test_insertion_shift_sort
insertion_binary_shift:
	pytest -v -s --durations=0 test_sorts.py::test_insertion_binary_shift_sort
shell:
	pytest -v -s --durations=0 test_sorts.py::test_shell_sort